import { Translations, LocationTag, CategoryId, Listing, EmergencyContact, Store } from './types';

export const LOCATIONS: LocationTag[] = [
  { id: 'cbd', name: 'Malindi CBD' },
  { id: 'barani', name: 'Barani' },
  { id: 'shella', name: 'Shella' },
  { id: 'watamu', name: 'Watamu' },
  { id: 'mambrui', name: 'Mambrui' },
  { id: 'msabaha', name: 'Msabaha' },
  { id: 'mayungu', name: 'Mayungu' },
];

export const CATEGORIES: { id: CategoryId; label: { en: string; sw: string }; icon: string }[] = [
  { id: 'market', label: { en: 'Buy & Sell', sw: 'Nunua & Uza' }, icon: '🛍️' },
  { id: 'gigs', label: { en: 'Quick Gigs', sw: 'Vibarua' }, icon: '⚡' },
  { id: 'stays', label: { en: 'Stays', sw: 'Malazi' }, icon: '🏠' },
  { id: 'services', label: { en: 'Services', sw: 'Huduma' }, icon: '🛠️' },
  { id: 'food', label: { en: 'Food', sw: 'Chakula' }, icon: '🍔' },
  { id: 'rides', label: { en: 'Rides', sw: 'Usafiri' }, icon: '🚕' },
  { id: 'jobs', label: { en: 'Jobs', sw: 'Kazi' }, icon: '💼' },
  { id: 'deals', label: { en: 'Deals', sw: 'Dili' }, icon: '🔥' },
  { id: 'lostfound', label: { en: 'Lost & Found', sw: 'Waliopotea' }, icon: '🔍' },
  { id: 'emergency', label: { en: 'Emergency', sw: 'Dharura' }, icon: '🚑' },
];

export const UI_TEXT: Translations = {
  welcome: { en: 'Mali Safi. Bei Safi. Deal Safi.', sw: 'Mali Safi. Bei Safi. Deal Safi.' },
  subtitle: { en: 'The best marketplace for Malindi & Watamu', sw: 'Soko bora la Malindi na Watamu' },
  searchPlaceholder: { en: 'Search for phone, fundi, villa...', sw: 'Tafuta simu, fundi, nyumba...' },
  postButton: { en: 'Post Item', sw: 'Weka Tangazo' },
  recentListings: { en: 'Fresh in Malindi', sw: 'Mpya Malindi' },
  featured: { en: 'Featured', sw: 'Imependekezwa' },
  chat: { en: 'Chat', sw: 'Chati' },
  viewDetails: { en: 'View Details', sw: 'Ona Zaidi' },
  loading: { en: 'Loading...', sw: 'Inapakia...' },
  price: { en: 'Price', sw: 'Bei' },
  location: { en: 'Location', sw: 'Mahali' },
  description: { en: 'Description', sw: 'Maelezo' },
  verifiedSeller: { en: 'Verified Seller', sw: 'Muuzaji Aliyehakikiwa' },
  reportScam: { en: 'Report Scammer', sw: 'Ripoti Tapeli' },
  safetyTip: { en: 'Safety Tip: Meet in public places. Do not pay in advance.', sw: 'Ushauri: Kutana sehemu ya wazi. Usilipe kabla ya kuona bidhaa.' },
  uploadImage: { en: 'Upload Photo', sw: 'Pakia Picha' },
  titleLabel: { en: 'Title', sw: 'Kichwa' },
  categoryLabel: { en: 'Category', sw: 'Kitengo' },
  descLabel: { en: 'Description', sw: 'Maelezo' },
  priceLabel: { en: 'Price (KES)', sw: 'Bei (KES)' },
  phoneLabel: { en: 'WhatsApp Number', sw: 'Namba ya WhatsApp' },
  submit: { en: 'Post Now', sw: 'Weka Sasa' },
  aiHelp: { en: 'Generate with AI', sw: 'Tengeneza na AI' },
  quickGig: { en: 'Quick 24h Gig', sw: 'Kibarua (24h)' },
  quickGigHelp: { en: 'Post a job that expires in 24 hours.', sw: 'Weka kazi ya dharura inayoisha baada ya masaa 24.' },
  quickGigsHeader: { en: '⚡ Quick Gigs (24h)', sw: '⚡ Vibarua vya Leo' },
  shopsHeader: { en: 'Shops & Stalls', sw: 'Maduka & Vibanda' },
  openShop: { en: 'Open Shop', sw: 'Fungua Duka' },
  visitShop: { en: 'Visit Shop', sw: 'Tembelea Duka' },
  itemsCount: { en: 'Items', sw: 'Bidhaa' },
};

export const MOCK_EMERGENCY: EmergencyContact[] = [
  { name: 'Malindi Police Station', phone: '999', category: 'Police' },
  { name: 'Tawfiq Hospital', phone: '+254700000000', category: 'Medical' },
  { name: 'Malindi Fire Station', phone: '0422120430', category: 'Fire' },
  { name: 'Kenya Power Emergency', phone: '97771', category: 'Utility' },
];

export const MOCK_STORES: Store[] = [
  {
    id: 'store1',
    name: 'Ahmed Phones & Tech',
    description: 'Tunauza simu mpya na used, charger na earphones. Repair pia tunafanya.',
    location: 'Malindi Complex',
    image_url: 'https://picsum.photos/100/100?random=101',
    cover_url: 'https://picsum.photos/800/300?random=102',
    whatsapp: '254712345678',
    is_verified: true,
    category: 'Electronics'
  },
  {
    id: 'store2',
    name: 'Mama K Kiosk',
    description: 'Fresh vegetables, fruits and blended juice delivered to your home.',
    location: 'Shella Market',
    image_url: 'https://picsum.photos/100/100?random=103',
    cover_url: 'https://picsum.photos/800/300?random=104',
    whatsapp: '254722000000',
    is_verified: true,
    category: 'Food'
  },
  {
    id: 'store3',
    name: 'Watamu Surf & Thrift',
    description: 'Beach wear, surf boards rental and thrift clothes.',
    location: 'Watamu Beach Road',
    image_url: 'https://picsum.photos/100/100?random=105',
    cover_url: 'https://picsum.photos/800/300?random=106',
    whatsapp: '254733000000',
    is_verified: false,
    category: 'Fashion'
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'iPhone 12 Pro Max - 128GB',
    description: 'Simu safi sana. Battery health 90%. Comes with charger. Meet in town.',
    price: 65000,
    category: 'market',
    location: 'Malindi CBD',
    image_url: 'https://picsum.photos/400/300?random=1',
    whatsapp: '254712345678',
    is_featured: true,
    is_verified: true,
    created_at: new Date().toISOString(),
    views: 120,
    user_name: 'Ahmed Phones',
    store_id: 'store1'
  },
  {
    id: 'gig1',
    title: 'Need 2 people to carry sand',
    description: 'Urgent at Shella beach. Cash payment immediately.',
    price: 500,
    category: 'gigs',
    location: 'Shella',
    image_url: 'https://picsum.photos/400/300?random=10',
    whatsapp: '254712345678',
    is_featured: false,
    is_verified: true,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    views: 450,
    user_name: 'Construction Boss'
  },
  {
    id: 'gig2',
    title: 'Dishwasher for busy night',
    description: 'Busy restaurant in town needs extra hand tonight 6pm-11pm.',
    price: 800,
    category: 'gigs',
    location: 'Malindi CBD',
    image_url: 'https://picsum.photos/400/300?random=11',
    whatsapp: '254700000000',
    is_featured: false,
    is_verified: true,
    created_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    views: 200,
    user_name: 'Swahili Dishes'
  },
  {
    id: '2',
    title: 'Fundi wa Mabomba (Plumber)',
    description: 'Expert plumber available for repairs and installation within Malindi and Watamu.',
    price: 500,
    category: 'services',
    location: 'Barani',
    image_url: 'https://picsum.photos/400/300?random=2',
    whatsapp: '254700000000',
    is_featured: false,
    is_verified: true,
    created_at: new Date().toISOString(),
    views: 45,
    user_name: 'Fundi Juma'
  },
  {
    id: '3',
    title: 'Beachfront Villa Watamu',
    description: '3 Bedroom villa with pool. Available for short stays and parties.',
    price: 15000,
    category: 'stays',
    location: 'Watamu',
    image_url: 'https://picsum.photos/400/300?random=3',
    whatsapp: '254722222222',
    is_featured: true,
    is_verified: true,
    created_at: new Date().toISOString(),
    views: 800,
    user_name: 'Coast Stays'
  },
  {
    id: '4',
    title: 'Toyota Vitz 2015',
    description: 'Buy and drive. Low mileage. Lady owner.',
    price: 650000,
    category: 'market',
    location: 'Mambrui',
    image_url: 'https://picsum.photos/400/300?random=4',
    whatsapp: '254733333333',
    is_featured: false,
    is_verified: false,
    created_at: new Date().toISOString(),
    views: 300,
    user_name: 'Car Bazaar'
  },
   {
    id: '5',
    title: 'House Girl Needed',
    description: 'Looking for a serious house help. Must be good with kids. Salary negotiable.',
    price: 8000,
    category: 'jobs',
    location: 'Shella',
    image_url: 'https://picsum.photos/400/300?random=5',
    whatsapp: '254733333333',
    is_featured: false,
    is_verified: true,
    created_at: new Date().toISOString(),
    views: 50,
    user_name: 'Mama K',
    store_id: 'store2'
  },
  {
    id: '6',
    title: 'Samsung S21',
    description: 'Clean samsung phone.',
    price: 45000,
    category: 'market',
    location: 'Malindi Complex',
    image_url: 'https://picsum.photos/400/300?random=6',
    whatsapp: '254712345678',
    is_featured: false,
    is_verified: true,
    created_at: new Date().toISOString(),
    views: 30,
    user_name: 'Ahmed Phones',
    store_id: 'store1'
  },
  {
    id: '7',
    title: 'Vintage Shirt',
    description: 'Floral shirt size L.',
    price: 1200,
    category: 'market',
    location: 'Watamu',
    image_url: 'https://picsum.photos/400/300?random=7',
    whatsapp: '254733000000',
    is_featured: false,
    is_verified: false,
    created_at: new Date().toISOString(),
    views: 12,
    user_name: 'Watamu Surf',
    store_id: 'store3'
  }
];